version: "3"

services:
  nginx:
    build:
      context: ./docker
      dockerfile: ./Dockerfile-ngnix
    volumes:
      - ./:/var/www/form-task/:cached
    ports:
      - 10302:80
      - 10303:8000
    networks:
      - symfony

  fpm:
    build:
      context: ./docker
      dockerfile: ./Dockerfile-php
    environment:
      - DATABASE_URL=mysql://root:root@db/docker_sf
    volumes:
      - ./:/var/www/form-task/:cached
    networks:
      - symfony
    user: ${CURRENT_HOST_USER}

  db:
    image: mariadb:10.2.29
    ports:
      - "3317:3306"
    environment:
      - MYSQL_DATABASE=docker_sf
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - persistent:/var/lib/mysql
      - ./docker/build/db/:/docker-entrypoint-initdb.d/
    networks:
      - symfony

networks:
  symfony:
    driver: bridge

volumes:
  persistent: